---
# by Waldemar Baldowski
- hosts: all
  gather_facts: no

  tasks:

  - name: Create folders
    file:
     path: /tmp/{{ item }}
     state: directory
     mode: '0750'
    loop:
     - one
     - two
     - three
    register: a_output

  - name: Disply output
    debug:
     var: a_output
     
# end.
