---
# by Waldemar Baldowski
- hosts: all
  gather_facts: no

  vars:
   folders:
    - one
    - two
    - three

  tasks:

  - name: Create folders {{ folders }}
    file:
     path: /tmp/{{ item }}
     state: directory
     mode: '0750'
    loop: "{{ folders }}"
    register: a_output

  - name: Disply output
    debug:
     var: a_output

# end.
