---
# by Waldemar Bałdowski
# usage: ansible-playbook -i inventory --extra-vars="a_firewall_port=9090/tcp" firewall-rule.yml
- name: Implement firewall rule

  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root

  ####
  vars:
    a_firewall_port: 8080/tcp

  tasks:

  - name: Open firewall port defined in variable {{ a_firewall_port }}
    firewalld:
     port: "{{ a_firewall_port }}"
     permanent: yes
     immediate: yes
     state: enabled
     zone: public

## end.
