---
# by Waldemar Bałdowski
# usage: ansible-playbook -i inventory --limit group1 restart-ssh.yml
# setup become params in /etc/ansible/ansible.cfg or use --ask-sudo-pass paramater for ansible-playbook command
- name: Restart sshd and check service status

  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root

  tasks:

    - name: Restart sshd
      service:
       name: sshd
       state: restarted
       enabled: yes

    - name: Chesk sshd status
      command: systemctl status sshd
      register: a_ssh_status

    - name: Show status
      debug:
       var: a_ssh_status.stdout_lines

## end.
